Repository Learn-Write-Repeat/Open-contributions, pull requests merged in 2021-10, with the labels that each got.

#369 Update Aditya_OpenCV_Yolov3.md
  Aditya_Mahimkar_OpenCV/Aditya_OpenCV_Yolov3.md
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#370 Updated file request
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted, hacktoberfest2021

#371 Added Blockchain topic
  README.md
Labels: Hacktoberfest, digitalocean, hacktoberfest-accepted, hacktoberfest2021

#373 Added tutorial
  Anshul_ML_regression.md
Labels: documentation, Hacktoberfest, digitalocean, hacktoberfest-accepted, hacktoberfest2021

#374 Create Visualization.md
  Visualization.md
Labels: Hacktoberfest, datascience, digitalocean, hacktoberfest-accepted, hacktoberfest2021

#375 Create KNN.md
  KNN.md
Labels: datascience, digitalocean, hacktoberfest-accepted, hacktoberfest2021

#356 Overview of Machine Learning (Module 2 assignment)
  GauravSewatkar.md
Labels: datascience, digitalocean, hacktoberfest-accepted, hacktoberfest2021

#376 Create smrtcontract.sol
  NonFungibleToken/smrtcontract.sol
Labels: Hacktoberfest, digitalocean, hacktoberfest-accepted, hacktoberfest2021

#377 Added metadata for API
  NonFungibleToken/id
Labels: Hacktoberfest, digitalocean, hacktoberfest-accepted, hacktoberfest2021

#378 script file for minting
  NonFungibleToken/mint
Labels: Hacktoberfest, digitalocean, hacktoberfest-accepted, hacktoberfest2021

#379 Create Readme.md
  NonFungibleToken/Readme.md
Labels: Hacktoberfest, digitalocean, hacktoberfest-accepted, hacktoberfest2021
